### ISSUE TITLE
Combination of packages from conda /pip bayeux-ml  make pytensor to fail on Apple Sillicon (Accelerate problem)

### ISSUE THREAD

**Issue by danieltomasz** [pymc-devs/pytensor#1134]
### Describe the issue:

I cannot reproduce it with substantially smaller conda.yml
```
channels:
  - conda-forge
dependencies:
- numba
- python>=3.12.8
- matplotlib
- seaborn
- conda
- plotnine
- ipykernel
- polars
- pandas
- arviz
- pymc>=5.19
- statsmodels
- nibabel
- nilearn
- bambi
- tqdm
- templateflow
- nutpie
- pyarrow
- pytest
- preliz
- pip 
- ipywidgets
- pip:
  - bayeux-ml==0.1.14
  - watermark
  - nbconvert
```

with this code
```python
import numpy as np
import pandas as pd
import pymc as pm
import preliz as pz

np.random.seed(123)
trials = 4
theta_real = 0.35  # unknown value in a real experiment
data = pz.Binomial(n=1, p=theta_real).rvs(trials)
data

with pm.Model() as our_first_model:
    θ = pm.Beta("θ", alpha=1.0, beta=1.0)
    y = pm.Bernoulli("y", p=θ, observed=data)
    idata = pm.sample(1000, random_seed=4591)
```

and this error
```
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Initializing NUTS using jitter+adapt_diag...
ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: True_div(1.0, 2.0)
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/graph/rewriting/basic.py", line 1913, in process_node
    replacements = node_rewriter.transform(fgraph, node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/graph/rewriting/basic.py", line 1085, in transform
    return self.fn(fgraph, node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/tensor/rewriting/basic.py", line 1166, in constant_folding
    return unconditional_constant_folding.transform(fgraph, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/graph/rewriting/basic.py", line 1085, in transform
    return self.fn(fgraph, node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/tensor/rewriting/basic.py", line 1115, in unconditional_constant_folding
    thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/link/c/op.py", line 119, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/link/c/op.py", line 84, in make_c_thunk
    outputs = cl.make_thunk(
              ^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/link/c/basic.py", line 1186, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
                                                             ^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/link/c/basic.py", line 1103, in __compile__
    thunk, module = self.cthunk_factory(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/link/c/basic.py", line 1631, in cthunk_factory
    module = cache.module_from_key(key=key, lnk=self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/link/c/cmodule.py", line 1255, in module_from_key
    module = lnk.compile_cmodule(location)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/link/c/basic.py", line 1532, in compile_cmodule
    module = c_compiler.compile_str(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/link/c/cmodule.py", line 2685, in compile_str
    raise CompileError(
pytensor.link.c.exceptions.CompileError: Compilation failed (return status=1):
[/Users/daniel/.pyenv/versions/bayes-3.12/bin/clang](https://file+.vscode-resource.vscode-cdn.net/Users/daniel/.pyenv/versions/bayes-3.12/bin/clang)++ -dynamiclib -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -fPIC -undefined dynamic_lookup -ld64 -I/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/numpy/core/include -I/Users/daniel/.pyenv/versions/miniconda3-3.12-24.9.2-0/envs/bayes-3.12/include/python3.12 -I/Users/daniel/.pyenv/versions/bayes-3.12/lib/python3.12/site-packages/pytensor/link/c/c_code -L/Users/daniel/.pyenv/versions/bayes-3.12/lib -fvisibility=hidden -o [/Users/daniel/.pytensor/compiledir_macOS-15.2-arm64-arm-64bit-arm-3.12.8-64/tmppzr08drd/ma0f967fdf213fde876a01df8ebb84f144c12ad106659a1ea1a5fece49a3a9fa7.so](https://file+.vscode-resource.vscode-cdn.net/Users/daniel/.pytensor/compiledir_macOS-15.2-arm64-arm-64bit-arm-3.12.8-64/tmppzr08drd/ma0f967fdf213fde876a01df8ebb84f144c12ad106659a1ea1a5fece49a3a9fa7.so) [/Users/daniel/.pytensor/compiledir_macOS-15.2-arm64-arm-64bit-arm-3.12.8-64/tmppzr08drd/mod.cpp](https://file+.vscode-resource.vscode-cdn.net/Users/daniel/.pytensor/compiledir_macOS-15.2-arm64-arm-64bit-arm-3.12.8-64/tmppzr08drd/mod.cpp)
ld: library not found for -ld64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

while when I am using a  smaller dependencies like here 

```
channels:
  - conda-forge
dependencies:
  - numba
  - python>=3.12.8
  - pytensor
  - libblas=*=*accelerate
  - pip
  - nutpie
  - preliz
  - arviz
  - bambi
  - ipykernel
  - pymc
  - ipywidgets
  - pyarrow
  - pip:
    - bayeux-ml==0.1.15
    
````
the kernel with aboveinstalled package seems to work

### Reproducable code example:

```python
import numpy as np
import pandas as pd
import pymc as pm
import preliz as pz

np.random.seed(123)
trials = 4
theta_real = 0.35  # unknown value in a real experiment
data = pz.Binomial(n=1, p=theta_real).rvs(trials)
data

with pm.Model() as our_first_model:
    θ = pm.Beta("θ", alpha=1.0, beta=1.0)
    y = pm.Bernoulli("y", p=θ, observed=data)
    idata = pm.sample(1000, random_seed=4591)
```

### PyTensor version information:

PyTensor version: 2.26.4
PyMC version: 5.19.1

### Context for the issue:

MacOS 15.2

**Comment by danieltomasz** [comment]
The issue is conda version conflic, few day ago new conda was release and probably there is some mix up with conda and package version, this is problaby on tangentially pytensor related
