### ISSUE TITLE
Assertion Error raised by local_IncSubtensor_serialize rewrite

### ISSUE THREAD

**Issue by bpajusco** [pymc-devs/pytensor#279]
### Describe the issue:

I've just reinstalled anaconda on arm MAC to take advantage of the native implementation and suddenly pymc stopped working on what looks like a pytensor issue. This happens when I try to sample for a somewhat structured GP with latent and sparse features as well as co-regionalisation. Interestingly jax sampling works (though is very slow) but numba based acceleration as well as standard pymc fail before compiling the graph with the following assertion error

```python

ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: local_IncSubtensor_serialize
ERROR (pytensor.graph.rewriting.basic): node: Elemwise{add,no_inplace}(AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}.0, AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}.0)
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "/Users/bpajusco/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py", line 1933, in process_node
    replacements = node_rewriter.transform(fgraph, node)
  File "/Users/bpajusco/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py", line 1092, in transform
    return self.fn(fgraph, node)
  File "/Users/bpajusco/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/tensor/rewriting/subtensor.py", line 1197, in local_IncSubtensor_serialize
    assert mi.owner.inputs[0].type.is_super(tip.type)
AssertionError

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[8], line 2
      1 with lcm:
----> 2     mogp_trace = pm.sample(draws=1000, tune=1000, nuts={'target_accept':0.9})

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pymc/sampling/mcmc.py:447, in sample(draws, step, init, n_init, initvals, trace, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, callback, jitter_max_retries, return_inferencedata, keep_warning_stat, idata_kwargs, mp_ctx, **kwargs)
    444         auto_nuts_init = False
    446 initial_points = None
--> 447 step = assign_step_methods(model, step, methods=pm.STEP_METHODS, step_kwargs=kwargs)
    449 if isinstance(step, list):
    450     step = CompoundStep(step)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pymc/sampling/mcmc.py:189, in assign_step_methods(model, step, methods, step_kwargs)
    181         selected = max(
    182             methods,
    183             key=lambda method, var=rv_var, has_gradient=has_gradient: method._competence(
    184                 var, has_gradient
    185             ),
    186         )
    187         selected_steps[selected].append(var)
--> 189 return instantiate_steppers(model, steps, selected_steps, step_kwargs)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pymc/sampling/mcmc.py:107, in instantiate_steppers(model, steps, selected_steps, step_kwargs)
    105         args = step_kwargs.get(step_class.name, {})
    106         used_keys.add(step_class.name)
--> 107         step = step_class(vars=vars, model=model, **args)
    108         steps.append(step)
    110 unused_args = set(step_kwargs).difference(used_keys)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pymc/step_methods/hmc/nuts.py:182, in NUTS.__init__(self, vars, max_treedepth, early_max_treedepth, **kwargs)
    124 def __init__(self, vars=None, max_treedepth=10, early_max_treedepth=8, **kwargs):
    125     r"""Set up the No-U-Turn sampler.
    126 
    127     Parameters
   (...)
    180     `pm.sample` to the desired number of tuning steps.
    181     """
--> 182     super().__init__(vars, **kwargs)
    184     self.max_treedepth = max_treedepth
    185     self.early_max_treedepth = early_max_treedepth

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pymc/step_methods/hmc/base_hmc.py:109, in BaseHMC.__init__(self, vars, scaling, step_scale, is_cov, model, blocked, potential, dtype, Emax, target_accept, gamma, k, t0, adapt_step_size, step_rand, **pytensor_kwargs)
    107 else:
    108     vars = get_value_vars_from_user_vars(vars, self._model)
--> 109 super().__init__(vars, blocked=blocked, model=self._model, dtype=dtype, **pytensor_kwargs)
    111 self.adapt_step_size = adapt_step_size
    112 self.Emax = Emax

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pymc/step_methods/arraystep.py:263, in GradientSharedStep.__init__(self, vars, model, blocked, dtype, logp_dlogp_func, **pytensor_kwargs)
    260 model = modelcontext(model)
    262 if logp_dlogp_func is None:
--> 263     func = model.logp_dlogp_function(vars, dtype=dtype, **pytensor_kwargs)
    264 else:
    265     func = logp_dlogp_func

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pymc/model.py:648, in Model.logp_dlogp_function(self, grad_vars, tempered, **kwargs)
    642 ip = self.initial_point(0)
    643 extra_vars_and_values = {
    644     var: ip[var.name]
    645     for var in self.value_vars
    646     if var in input_vars and var not in grad_vars
    647 }
--> 648 return ValueGradFunction(costs, grad_vars, extra_vars_and_values, **kwargs)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pymc/model.py:389, in ValueGradFunction.__init__(self, costs, grad_vars, extra_vars_and_values, dtype, casting, compute_grads, **kwargs)
    385     outputs = [cost]
    387 inputs = grad_vars
--> 389 self._pytensor_function = compile_pymc(inputs, outputs, givens=givens, **kwargs)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pymc/pytensorf.py:1121, in compile_pymc(inputs, outputs, random_seed, mode, **kwargs)
   1119 opt_qry = mode.provided_optimizer.including("random_make_inplace", check_parameter_opt)
   1120 mode = Mode(linker=mode.linker, optimizer=opt_qry)
-> 1121 pytensor_function = pytensor.function(
   1122     inputs,
   1123     outputs,
   1124     updates={**rng_updates, **kwargs.pop("updates", {})},
   1125     mode=mode,
   1126     **kwargs,
   1127 )
   1128 return pytensor_function

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/compile/function/__init__.py:315, in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    309     fn = orig_function(
    310         inputs, outputs, mode=mode, accept_inplace=accept_inplace, name=name
    311     )
    312 else:
    313     # note: pfunc will also call orig_function -- orig_function is
    314     #      a choke point that all compilation must pass through
--> 315     fn = pfunc(
    316         params=inputs,
    317         outputs=outputs,
    318         mode=mode,
    319         updates=updates,
    320         givens=givens,
    321         no_default_updates=no_default_updates,
    322         accept_inplace=accept_inplace,
    323         name=name,
    324         rebuild_strict=rebuild_strict,
    325         allow_input_downcast=allow_input_downcast,
    326         on_unused_input=on_unused_input,
    327         profile=profile,
    328         output_keys=output_keys,
    329     )
    330 return fn

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/compile/function/pfunc.py:367, in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys, fgraph)
    353     profile = ProfileStats(message=profile)
    355 inputs, cloned_outputs = construct_pfunc_ins_and_outs(
    356     params,
    357     outputs,
   (...)
    364     fgraph=fgraph,
    365 )
--> 367 return orig_function(
    368     inputs,
    369     cloned_outputs,
    370     mode,
    371     accept_inplace=accept_inplace,
    372     name=name,
    373     profile=profile,
    374     on_unused_input=on_unused_input,
    375     output_keys=output_keys,
    376     fgraph=fgraph,
    377 )

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/compile/function/types.py:1754, in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys, fgraph)
   1752 try:
   1753     Maker = getattr(mode, "function_maker", FunctionMaker)
-> 1754     m = Maker(
   1755         inputs,
   1756         outputs,
   1757         mode,
   1758         accept_inplace=accept_inplace,
   1759         profile=profile,
   1760         on_unused_input=on_unused_input,
   1761         output_keys=output_keys,
   1762         name=name,
   1763         fgraph=fgraph,
   1764     )
   1765     with config.change_flags(compute_test_value="off"):
   1766         fn = m.create(defaults)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/compile/function/types.py:1524, in FunctionMaker.__init__(self, inputs, outputs, mode, accept_inplace, function_builder, profile, on_unused_input, fgraph, output_keys, name, no_fgraph_prep)
   1521 self.fgraph = fgraph
   1523 if not no_fgraph_prep:
-> 1524     self.prepare_fgraph(inputs, outputs, found_updates, fgraph, mode, profile)
   1526 assert len(fgraph.outputs) == len(outputs + found_updates)
   1528 # The 'no_borrow' outputs are the ones for which that we can't
   1529 # return the internal storage pointer.

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/compile/function/types.py:1416, in FunctionMaker.prepare_fgraph(inputs, outputs, additional_outputs, fgraph, mode, profile)
   1409 rewrite_time = None
   1411 with config.change_flags(
   1412     mode=mode,
   1413     compute_test_value=config.compute_test_value_opt,
   1414     traceback__limit=config.traceback__compile_limit,
   1415 ):
-> 1416     rewriter_profile = rewriter(fgraph)
   1418     end_rewriter = time.perf_counter()
   1419     rewrite_time = end_rewriter - start_rewriter

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py:135, in GraphRewriter.__call__(self, fgraph)
    133 def __call__(self, fgraph):
    134     """Rewrite a `FunctionGraph`."""
--> 135     return self.rewrite(fgraph)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py:131, in GraphRewriter.rewrite(self, fgraph, *args, **kwargs)
    122 """
    123 
    124 This is meant as a shortcut for the following::
   (...)
    128 
    129 """
    130 self.add_requirements(fgraph)
--> 131 return self.apply(fgraph, *args, **kwargs)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py:302, in SequentialGraphRewriter.apply(self, fgraph)
    300 nb_nodes_before = len(fgraph.apply_nodes)
    301 t0 = time.perf_counter()
--> 302 sub_prof = rewriter.apply(fgraph)
    303 l.append(float(time.perf_counter() - t0))
    304 sub_profs.append(sub_prof)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py:2051, in WalkingGraphRewriter.apply(self, fgraph, start_from)
   2049             continue
   2050         current_node = node
-> 2051         nb += self.process_node(fgraph, node)
   2052     loop_t = time.perf_counter() - t0
   2053 finally:

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py:1936, in NodeProcessingGraphRewriter.process_node(self, fgraph, node, node_rewriter)
   1934 except Exception as e:
   1935     if self.failure_callback is not None:
-> 1936         self.failure_callback(
   1937             e, self, [(x, None) for x in node.outputs], node_rewriter, node
   1938         )
   1939         return False
   1940     else:

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py:1789, in NodeProcessingGraphRewriter.warn_inplace(cls, exc, nav, repl_pairs, node_rewriter, node)
   1787 if isinstance(exc, InconsistencyError):
   1788     return
-> 1789 return cls.warn(exc, nav, repl_pairs, node_rewriter, node)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py:1777, in NodeProcessingGraphRewriter.warn(cls, exc, nav, repl_pairs, node_rewriter, node)
   1773     pdb.post_mortem(sys.exc_info()[2])
   1774 elif isinstance(exc, AssertionError) or config.on_opt_error == "raise":
   1775     # We always crash on AssertionError because something may be
   1776     # seriously wrong if such an exception is raised.
-> 1777     raise exc

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py:1933, in NodeProcessingGraphRewriter.process_node(self, fgraph, node, node_rewriter)
   1931 assert node_rewriter is not None
   1932 try:
-> 1933     replacements = node_rewriter.transform(fgraph, node)
   1934 except Exception as e:
   1935     if self.failure_callback is not None:

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/graph/rewriting/basic.py:1092, in FromFunctionNodeRewriter.transform(self, fgraph, node)
   1087     if not (
   1088         node.op in self._tracks or isinstance(node.op, self._tracked_types)
   1089     ):
   1090         return False
-> 1092 return self.fn(fgraph, node)

File ~/anaconda3/envs/pymc/lib/python3.10/site-packages/pytensor/tensor/rewriting/subtensor.py:1197, in local_IncSubtensor_serialize(fgraph, node)
   1195 for mi in movable_inputs:
   1196     assert o_type.is_super(tip.type)
-> 1197     assert mi.owner.inputs[0].type.is_super(tip.type)
   1198     tip = mi.owner.op(tip, *mi.owner.inputs[1:])
   1199     # Copy over stacktrace from outputs of the original
   1200     # "movable" operation to the new operation.

AssertionError: 

```

Here is the code for reference:

```python

class SparseLatent:
    def __init__(self, cov_func):
        self.cov = cov_func

    def prior(self, name, X, Xu):
        Kuu = self.cov(Xu)
        self.L = pm.gp.util.cholesky(pm.gp.util.stabilize(Kuu))
        self.v = pm.Normal(f"u_rotated_{name}", mu=0.0, sigma=1.0, shape=len(Xu))
        self.u = pm.Deterministic(f"u_{name}", pt.dot(self.L, self.v))

        Kfu = self.cov(X, Xu)
        self.Kuiu = pm.gp.util.solve_upper(
            self.L.T, pm.gp.util.solve_lower(self.L, self.u)
        )
        self.mu = pm.Deterministic(f"mu_{name}", pt.dot(Kfu, self.Kuiu))
        return self.mu

    def conditional(self, name, Xnew, Xu):
        Ksu = self.cov(Xnew, Xu)
        mus = pt.dot(Ksu, self.Kuiu)
        tmp = pm.gp.util.solve_lower(self.L, Ksu.T)
        Qss = pt.dot(tmp.T, tmp)  # Qss = tt.dot(tt.dot(Ksu, tt.nlinalg.pinv(Kuu)), Ksu.T)
        Kss = self.cov(Xnew)
        Lss = pm.gp.util.cholesky(pm.gp.util.stabilize(Kss - Qss))
        mu_pred = pm.MvNormal(name, mu=mus, chol=Lss, shape=len(Xnew))
        return mu_pred

with pm.Model() as lcm:
    # Define kernel structure
    kernels = [pm.gp.cov.ExpQuad, pm.gp.cov.Matern32, pm.gp.cov.Periodic]
    # Priors
    ℓ = pm.Gamma("ℓ", alpha=2, beta=0.5, shape=len(kernels))
    η = pm.Gamma("η", alpha=3, beta=1, shape=len(kernels))
    per = pm.Gamma(name='per', alpha=30, beta=2)
   
    

    # Define a list of covariance functions
    cov_list = [
        η[idx] ** 2 * kernel(input_dim=3, ls=ℓ[idx], active_dims=[0]) + pm.gp.cov.WhiteNoise(sigma=1e-6)
        if kernel!=pm.gp.cov.Periodic
        else
        η[idx] ** 2 * kernel(input_dim=3, period=per, ls=ℓ[idx], active_dims=[0]) + pm.gp.cov.WhiteNoise(sigma=1e-6)
    for idx, kernel in enumerate(kernels)
]
    
    # Get the LCM kernel
    cov_lcm = get_lcm(
        input_dim=3, active_dims=[1], num_outputs=len(tickers), kernels=cov_list
)

    # Define a Multi-output GP
    '''
    mogp = pm.gp.MarginalApprox(cov_func=cov_lcm) 
    Xu = data.loc[::5, ['x', 'output_idx']].values#pm.gp.util.kmeans_inducing_points(cond_points, X)
    y_ = mogp.marginal_likelihood("f", X=X, Xu=Xu, y=Y, sigma=σ)
    '''
    
    gp_lcm = SparseLatent(cov_func=cov_lcm)
    lcm_f = gp_lcm.prior("LCM", X_obs_c, Xu_c)

    μ_f = lcm_f[: len(Y)]
    lg_σ_f = lcm_f[len(Y) :len(Y)*2]
    σ_f = pm.Deterministic("σ_f", pm.math.exp(lg_σ_f))
    ν = pm.Gamma("ν", alpha=2, beta=0.1)
    

    #het_latent_gp = pm.Normal("het_latent_gp", mu=μ_f, sigma=σ_f, observed=Y)
    het_latent_gp = pm.StudentT("f", mu=μ_f, nu=ν, sigma=σ_f, observed=Y)


```

### Reproducable code example:

```python
class SparseLatent:
    def __init__(self, cov_func):
        self.cov = cov_func

    def prior(self, name, X, Xu):
        Kuu = self.cov(Xu)
        self.L = pm.gp.util.cholesky(pm.gp.util.stabilize(Kuu))
        self.v = pm.Normal(f"u_rotated_{name}", mu=0.0, sigma=1.0, shape=len(Xu))
        self.u = pm.Deterministic(f"u_{name}", pt.dot(self.L, self.v))

        Kfu = self.cov(X, Xu)
        self.Kuiu = pm.gp.util.solve_upper(
            self.L.T, pm.gp.util.solve_lower(self.L, self.u)
        )
        self.mu = pm.Deterministic(f"mu_{name}", pt.dot(Kfu, self.Kuiu))
        return self.mu

    def conditional(self, name, Xnew, Xu):
        Ksu = self.cov(Xnew, Xu)
        mus = pt.dot(Ksu, self.Kuiu)
        tmp = pm.gp.util.solve_lower(self.L, Ksu.T)
        Qss = pt.dot(tmp.T, tmp)  # Qss = tt.dot(tt.dot(Ksu, tt.nlinalg.pinv(Kuu)), Ksu.T)
        Kss = self.cov(Xnew)
        Lss = pm.gp.util.cholesky(pm.gp.util.stabilize(Kss - Qss))
        mu_pred = pm.MvNormal(name, mu=mus, chol=Lss, shape=len(Xnew))
        return mu_pred


with pm.Model() as lcm:
    # Define kernel structure
    kernels = [pm.gp.cov.ExpQuad, pm.gp.cov.Matern32, pm.gp.cov.Periodic]
    # Priors
    ℓ = pm.Gamma("ℓ", alpha=2, beta=0.5, shape=len(kernels))
    η = pm.Gamma("η", alpha=3, beta=1, shape=len(kernels))
    per = pm.Gamma(name='per', alpha=30, beta=2)
   
    

    # Define a list of covariance functions
    cov_list = [
        η[idx] ** 2 * kernel(input_dim=3, ls=ℓ[idx], active_dims=[0]) + pm.gp.cov.WhiteNoise(sigma=1e-6)
        if kernel!=pm.gp.cov.Periodic
        else
        η[idx] ** 2 * kernel(input_dim=3, period=per, ls=ℓ[idx], active_dims=[0]) + pm.gp.cov.WhiteNoise(sigma=1e-6)
    for idx, kernel in enumerate(kernels)
]
    
    # Get the LCM kernel
    cov_lcm = get_lcm(
        input_dim=3, active_dims=[1], num_outputs=len(tickers), kernels=cov_list
)

    # Define a Multi-output GP
    gp_lcm = SparseLatent(cov_func=cov_lcm)
    lcm_f = gp_lcm.prior("LCM", X_obs_c, Xu_c)

    μ_f = lcm_f[: len(Y)]
    lg_σ_f = lcm_f[len(Y) :len(Y)*2]
    σ_f = pm.Deterministic("σ_f", pm.math.exp(lg_σ_f))
    ν = pm.Gamma("ν", alpha=2, beta=0.1)
    

    #het_latent_gp = pm.Normal("het_latent_gp", mu=μ_f, sigma=σ_f, observed=Y)
    het_latent_gp = pm.StudentT("f", mu=μ_f, nu=ν, sigma=σ_f, observed=Y)
``


### Error message:

_No response_

### PyTensor version information:

I'm using MacOS Ventura 

### Context for the issue:

_No response_

**Comment by ricardoV94** [comment]
What PyTensor and PyMC versions are you using. If not the latest, can you try again with those?

**Comment by bpajusco** [comment]
I'm using the following versions for pymc and pytensor respectively.

pymc                      5.0.1                hd8ed1ab_0    conda-forge
pymc-base                 5.0.1              pyhd8ed1ab_0    conda-forge
pytensor                  2.8.11          py310ha090331_0    conda-forge
pytensor-base             2.8.11          py310hbe9552e_0    conda-forg

I note that I get the same compilation error when I try to use nutpie and when I use jax with numpyro the model runs but returns completely bogus results. It used to converge and fit the data quite nicely now it's a disaster. I wonder if there is something wrong with the Mac compilers conflicting with mamba/conda but have no idea.

I also went in and broke the code down to figure out what makes it fall over. The culprit is `pm.gp.cov.Coregion` and I have no real idea as to why this is happening. I'm using Coercion because I'm trying to build an lcm model and hear the code for that in case you had an interest. This code was running fine before I made changes to my setup and tried to use arm based conda in the hope of speeding up a few things here and there. Not only it didn't happen but everything is screwed up now

```python 

ef get_icm(input_dim, kernel, W=None, kappa=None, B=None, active_dims=None, name="ICM"):
    coreg = pm.gp.cov.Coregion(input_dim=input_dim, W=W, kappa=kappa, B=B, active_dims=active_dims)
    icm_cov = kernel * coreg  # Seperate input => Use Hadamard Product
    return icm_cov


def get_lcm(input_dim, active_dims, num_outputs, kernels, W=None, B=None, name="ICM"):
    """
    This function generates a LCM kernel from a list of input `kernels` and a Coregion kernel.
    """
    if B is None:
        κ = pm.Gamma(
            f"{name}_κ",
            alpha=5,
            beta=1,
            shape=num_outputs,
        )
        if W is None:
            W = pm.Normal(
                f"{name}_W",
                mu=0,
                sigma=5,
                shape=(num_outputs, 1),
                initval=np.random.randn(num_outputs, 1),
            )
    else:
        κ = None

    cov_func = 0
    for idx, kernel in enumerate(kernels):
        icm = get_icm(input_dim, kernel, W, κ, B, active_dims)
        cov_func += icm
    return cov_func

```

**Comment by ricardoV94** [comment]
> pymc 5.0.1 hd8ed1ab_0 conda-forge
pymc-base 5.0.1 pyhd8ed1ab_0 conda-forge

That's quite old already and I recall we fixed some issues along those lines. Can you try with the latest version (pymc 5.3.0 or 5.2. at least)

**Comment by bpajusco** [comment]
conda forge doesn't let you go any higher than what I have and weirdly enough everything works if I downgrade everything to pymc4 which I know we shouldn't do. I wonder if I wouldn't be better off cloning the repository and building from source though I'm not sure about dependencies as there might be some conflicts between pymc and numpy

**Comment by ricardoV94** [comment]
I see, I'll try to run your snippet myself to save you the trouble when I get some time!

**Comment by bpajusco** [comment]
No need thanks as I pip installed pymc 5.3.0. I'm having some other but this is now fixed
