### ISSUE TITLE
`local_add_neg_to_sub` rewrite gives wrong results with negative constants

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#584]
Reported in https://discourse.pymc.io/t/shape-issue-with-custom-logp-in-densitydist/13608/5?u=ricardov94

```python
import numpy as np

import pytensor
import pytensor.tensor as pt

x = pt.scalar("x")
neg_const = pt.as_tensor(np.full((10,), -0.1))
out = neg_const + x 

pytensor.function([x], out)
```
```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> The type of the replacement (Vector(float64, shape=(1,))) must be compatible with the type of the original Variable (Vector(float64, shape=(10,))). local_add_neg_to_sub
ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: local_add_neg_to_sub
ERROR (pytensor.graph.rewriting.basic): node: Add([-0.1 -0.1 ... -0.1 -0.1], ExpandDims{axis=0}.0)
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "/home/ricardo/Documents/Projects/pytensor/pytensor/graph/rewriting/basic.py", line 1968, in process_node
    fgraph.replace_all_validate_remove(  # type: ignore
  File "/home/ricardo/Documents/Projects/pytensor/pytensor/graph/features.py", line 626, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason=reason, **kwargs)
  File "/home/ricardo/Documents/Projects/pytensor/pytensor/graph/features.py", line 571, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False, **kwargs)
  File "/home/ricardo/Documents/Projects/pytensor/pytensor/graph/fg.py", line 508, in replace
    self.change_node_input(
  File "/home/ricardo/Documents/Projects/pytensor/pytensor/graph/fg.py", line 419, in change_node_input
    raise TypeError(
TypeError: The type of the replacement (Vector(float64, shape=(1,))) must be compatible with the type of the original Variable (Vector(float64, shape=(10,))).
```

https://github.com/pymc-devs/pytensor/blob/c52154d3116daa344e1abc53253d969b9fd0c181/pytensor/tensor/rewriting/math.py#L1897-L1922

The helper `get_constant` actually calls `get_unique_constant_value` under the hood, which in this case returns a single scalar, not the filled homogenous vector. The rewrite itself is also expecting only a scalar constant, otherwise it should be using `np.all`

**Comment by Armavica** [comment]
https://github.com/pymc-devs/pytensor/blob/c52154d3116daa344e1abc53253d969b9fd0c181/pytensor/tensor/rewriting/math.py#L1918-L1922

Do we actually want to keep this part? If it replaces `x + neg_const` with `x - pos_const`, is this actually useful?
Plus, doesn't this prevent things such as `-x + -6` from being rewritten as `-6 - x` (actually saving an op here)?

**Comment by ricardoV94** [comment]
Good point, it doesn't save us anything with a constant. Only reason would be for canonicalization but this is a specialization rewrite.

Will remove that branch and see if anything was relying on it
