### ISSUE TITLE
BUG: `tensordot` is broken

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pytensor#606]
### Describe the issue:

I recently needed to use `tensordot` and found that there are some concerning issues. The inferred `ndim` of the output tensor is incorrect, the `type.shape` are not propagated properly, and when it attempts to run the compiled thunk, it might kill the process (I don't know if it segfaults because tries to read bad memory) or, if you're lucky, it will simply complain about an incorrect shape broadcasting.

I managed to get a minimal reproducible example that fails and raises a `ValueError`. I wasn't able to get one that segfaults.

### Reproducable code example:

```python
import pytensor
from pytensor import tensor as pt
import numpy as np

H = np.ones((7, 3, 2))
x_val = np.ones(H.shape[-1])
x = pt.vector("x", shape=(H.shape[-1],))
y = pt.tensordot(x, H, axes=[[-1], [-1]])

y_val = np.tensordot(x_val, H, axes=[[-1], [-1]])

print(y.ndim, y_val.ndim)  # Prints out 4, 2
print(y.type.shape, y_val.ndim)  # Prints out (None, None, None, None), (7, 3)

f = pytensor.function([x], y)
f(x_val)  # Raises ValueError
```

### Error message:

```shell
<details>

ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: Reshape{2}([[[1. 1.] ... [1. 1.]]], [ 2 42])
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1922, in process_node
    replacements = node_rewriter.transform(fgraph, node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1082, in transform
    return self.fn(fgraph, node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/tensor/rewriting/basic.py", line 1106, in constant_folding
    required = thunk()
               ^^^^^^^
  File "~/repos/pytensor/pytensor/link/c/op.py", line 91, in rval
    thunk()
  File "~/repos/pytensor/pytensor/link/c/basic.py", line 1792, in __call__
    raise exc_value.with_traceback(exc_trace)
ValueError: cannot reshape array of size 42 into shape (2,42)

ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: Reshape{2}([[[1. 1.] ... [1. 1.]]], [ 2 42])
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1922, in process_node
    replacements = node_rewriter.transform(fgraph, node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1082, in transform
    return self.fn(fgraph, node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/tensor/rewriting/basic.py", line 1106, in constant_folding
    required = thunk()
               ^^^^^^^
  File "~/repos/pytensor/pytensor/link/c/op.py", line 91, in rval
    thunk()
  File "~/repos/pytensor/pytensor/link/c/basic.py", line 1792, in __call__
    raise exc_value.with_traceback(exc_trace)
ValueError: cannot reshape array of size 42 into shape (2,42)

ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: Reshape{2}([[[1. 1.] ... [1. 1.]]], [ 2 42])
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1922, in process_node
    replacements = node_rewriter.transform(fgraph, node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1082, in transform
    return self.fn(fgraph, node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/tensor/rewriting/basic.py", line 1106, in constant_folding
    required = thunk()
               ^^^^^^^
  File "~/repos/pytensor/pytensor/link/c/op.py", line 91, in rval
    thunk()
  File "~/repos/pytensor/pytensor/link/c/basic.py", line 1792, in __call__
    raise exc_value.with_traceback(exc_trace)
ValueError: cannot reshape array of size 42 into shape (2,42)

ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: Reshape{2}([[[1. 1.] ... [1. 1.]]], [ 2 42])
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1922, in process_node
    replacements = node_rewriter.transform(fgraph, node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1082, in transform
    return self.fn(fgraph, node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/tensor/rewriting/basic.py", line 1106, in constant_folding
    required = thunk()
               ^^^^^^^
  File "~/repos/pytensor/pytensor/link/c/op.py", line 91, in rval
    thunk()
  File "~/repos/pytensor/pytensor/link/c/basic.py", line 1792, in __call__
    raise exc_value.with_traceback(exc_trace)
ValueError: cannot reshape array of size 42 into shape (2,42)

ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: Reshape{2}([[[1. 1.] ... [1. 1.]]], [ 2 42])
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1922, in process_node
    replacements = node_rewriter.transform(fgraph, node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1082, in transform
    return self.fn(fgraph, node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/tensor/rewriting/basic.py", line 1106, in constant_folding
    required = thunk()
               ^^^^^^^
  File "~/repos/pytensor/pytensor/link/c/op.py", line 91, in rval
    thunk()
  File "~/repos/pytensor/pytensor/link/c/basic.py", line 1792, in __call__
    raise exc_value.with_traceback(exc_trace)
ValueError: cannot reshape array of size 42 into shape (2,42)

ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: Reshape{2}([[[1. 1.] ... [1. 1.]]], [ 2 42])
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1922, in process_node
    replacements = node_rewriter.transform(fgraph, node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/graph/rewriting/basic.py", line 1082, in transform
    return self.fn(fgraph, node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "~/repos/pytensor/pytensor/tensor/rewriting/basic.py", line 1106, in constant_folding
    required = thunk()
               ^^^^^^^
  File "~/repos/pytensor/pytensor/link/c/op.py", line 91, in rval
    thunk()
  File "~/repos/pytensor/pytensor/link/c/basic.py", line 1792, in __call__
    raise exc_value.with_traceback(exc_trace)
ValueError: cannot reshape array of size 42 into shape (2,42)

</details>
```

### PyTensor version information:

pytensor version: 2.18.6

**Comment by ricardoV94** [comment]
> the type.shape are not propagated properly

This is a nice have but not a must. PyTensor is only requires to propagate broadcastable info at write time.

Anyway, then loss likely comes from the Reshape Op.

The complicated tensordot should probably be a rewrite, as I'm aure JAX had a nice support for it without reshape tricks. Numba I don't know. 

Neither of these preclude just patching the current bug.

**Comment by ricardoV94** [comment]
> > the type.shape are not propagated properly
> 
> This is a nice have but not a must. PyTensor is only required to propagate broadcastable info at write time.
> 
> In any case, the loss likely comes from the Reshape Op.
> 
> The complicated tensordot should probably be a rewrite, as I'm sure JAX has a nice support for it without reshape tricks. Numba I don't know. 
> 
> Neither of these preclude just patching the current bug.

**Comment by lucianopaz** [comment]
I found that I can mostly copy over the implementation from [numpy](https://github.com/numpy/numpy/blob/v1.26.0/numpy/core/numeric.py#L932-L1122). The only stuff that I had to do differently is handling `broadcastable`, `x.type.shape` and `x.shape` properly to ensure everything runs smoothly.

The problem is that `numpy` has no implementation for `batched`, and to be honest, it seems to me like keeping `batched` versions of `dot` and `tensordot` is completely pointless. @ricardoV94, what do you think?

**Comment by ricardoV94** [comment]
I don't recall exactly what batched was doing. It uses `BatchedDot` to create a Batched TensorDot or something along those lines?

**Comment by ricardoV94** [comment]
> It treats the first dimension of the tensors as batches. Mostly like a crude `Blockwise`

If that is not being used anywhere in the codebase we can remove with perhaps an informative error message if anyone tries to call with the old signature. I think we can handle that better by trying to optimize Blockwise dots at compile time instead.

**Comment by ricardoV94** [comment]
Which dimension was assumed to be batched, the leading one? For backwards-compat you could just use `pt.vectorize`, and still start deprecating the kwarg (but at least code wouldn't be broken, just probably slower)
